spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/portfolio
    username: dev
    password: devpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
  thymeleaf:
    cache: false

logging:
  level:
    com.cesarvillarreal.portfolio: DEBUG
    org.flywaydb: DEBUG
